OnlineShop/OnlineShop/Controllers/VerifyController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DataAccess;
using OnlineShop.DataAccess.DAO;
using OnlineShop.Models;

namespace OnlineShop.Controllers
{
    public class VerifyController : Controller
    {
        private readonly UserDAO userDAO;
        public VerifyController()
        {
            userDAO = new UserDAO();
        }

        [HttpGet]
        public IActionResult Index(string email, string action)
        {
            var viewModel = new VerifyModel { Email = email, Action = action };
            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Index(VerifyModel model)
        {
            User user = await userDAO.GetUser(model.Email);

            if (model.Action.Equals("VerifyRegister", StringComparison.OrdinalIgnoreCase))
            {
                if (user != null && user.CodeVerify == model.VerificationCode)
                {
                    user.Status = true;
                    user.CodeVerify = null;
                    await userDAO.Update(user);
                    HttpContext.Session.SetString("Email", model.Email);
                    TempData["SuccessRegister"] = "Chúc mừng! Bạn đã kích hoạt tài khoản thành công.";
                }
                else
                {
                    TempData["Fail"] = "Mã xác thực không hợp lệ! Vui lòng kiểm tra lại.";
                }

            }
            else
            {
                if (user != null && user.CodeVerify == model.VerificationCode)
                {
                    user.Status = true;
                    user.CodeVerify = null;
                    await userDAO.Update(user);
                    HttpContext.Session.SetString("Email", model.Email);
                    TempData["SuccessLogin"] = "Chúc mừng! Bạn đã kích hoạt tài khoản thành công.";
                }
                else
                {
                    TempData["Fail"] = "Mã xác thực không hợp lệ! Vui lòng kiểm tra lại.";
                }
            }
            return View(model);
        }
    }
}

OnlineShop/OnlineShop/Views/Verify/Index.cshtml
@model VerifyModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Xác thực | Clothing Online Shop | Thương hiệu thời trang G1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Premium Bootstrap 4 Landing Page Template" />
    <meta name="keywords" content="Appointment, Booking, System, Dashboard, Health" />
    <meta name="author" content="Shreethemes" />
    <meta name="email" content="support@shreethemes.in" />
    <meta name="website" content="https://shreethemes.in" />
    <meta name="Version" content="v1.2.0" />
    <!-- favicon -->
    <link rel="shortcut icon" href="/lib/images/logoClothes.png">
    <!-- Bootstrap -->
    <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Icons -->
    <link href="/css/materialdesignicons.min.css" rel="stylesheet" type="text/css" />
    <link href="/css/remixicon.css" rel="stylesheet" type="text/css" />
    <link href="https://unicons.iconscout.com/release/v3.0.6/css/line.css" rel="stylesheet">
    <!-- Css -->
    <link href="/css/style.min.css" rel="stylesheet" type="text/css" id="theme-opt" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <style>
        .toast-top-right {
            top: 90px !important;
            right: 30px;
        }
    </style>
</head>

<body>
    <!-- Loader -->
    <div id="preloader">
        <div id="status">
            <div class="spinner">
                <div class="double-bounce1"></div>
                <div class="double-bounce2"></div>
            </div>
        </div>
    </div>
    <!-- Loader -->

    <div class="back-to-home rounded d-none d-sm-block">
        <a href="@Url.Action("Index", "Home")" class="btn btn-icon btn-info"><i data-feather="home" class="icons"></i></a>
    </div>

    <!-- Hero Start -->
    <section class="bg-home d-flex bg-light align-items-center" style="background: url('/lib/images/bg/background-thoi-trang-hien-dai-dep_025701441.jpg') center;">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5 col-md-8">
                    <div class="card login-page bg-white shadow mt-4 rounded border-0">
                        <div class="card-body">
                            <img style="border-radius: 25%;" src="/lib/images/logoClothes.png" height="60" width="110" class="mx-auto d-block" alt="">
                            <h4 class="text-center">Xác thực tài khoản</h4>
                            <br>
                            @using (Html.BeginForm("Index", "Verify", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken() <!--Gửi yêu cầu đến server từ Form có mã hóa token duy nhất-->
                                <div class="row">
                                    <div class="col-lg-12">
                                        <p class="text-muted">Vui lòng nhập mã code chúng tôi vừa gửi tới email <span class="text-danger">@Model.Email</span></p>
                                        <div class="mb-3">
                                            <label class="form-label">Mã xác thực <span class="text-danger">*</span></label>
                                            @Html.TextBoxFor(m => m.VerificationCode, new { @class = "form-control", placeholder = "Nhập mã xác thực", required = "required", type = "text"})
                                        </div>
                                    </div>
                                    <input type="hidden" name="email" value="@Model.Email" />
                                    <input type="hidden" name="action" value="@Model.Action" />
                                    <div class="col-lg-12">
                                        <div class="d-grid">
                                            <button class="btn btn-info">Xác Nhận</button>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div><!---->
                    <script>
                        $(document).ready(function () {
                            var message = '@TempData["SuccessRegister"]';
                            if (message !== '') {
                                toastr.success(message, '', {
                                    timeOut: 4000,
                                    showMethod: 'slideDown',
                                    hideMethod: 'slideUp'
                                });
                                setTimeout(function () {
                                    window.location.href = '/Home';
                                }, 5000); 
                            }
                        });
                    </script>

                    <script>
                        $(document).ready(function () {
                            var message = '@TempData["SuccessLogin"]';
                            if (message !== '') {
                                toastr.success(message, '', {
                                    timeOut: 4000,
                                    showMethod: 'slideDown', 
                                    hideMethod: 'slideUp'
                                });
                                setTimeout(function () {
                                    window.location.href = '/Home'; 
                                }, 5000); 
                            }
                        });
                    </script>
                    <script>
                        $(document).ready(function () {
                            var message = '@TempData["Fail"]';
                            if (message !== '') {
                                toastr.warning(message, '', {
                                    timeOut: 4000,
                                    showMethod: 'slideDown',
                                    hideMethod: 'slideUp'
                                });
                            }
                        });
                    </script>
                </div> <!--end col-->
            </div><!--end row-->
        </div> <!--end container-->
    </section><!--end section-->
    <!-- Hero End -->
    <!-- javascript -->
    <script src="../js/bootstrap.bundle.min.js"></script>
    <!-- Icons -->
    <script src="../js/feather.min.js"></script>
    <!-- Main Js -->
    <script src="../js/app.js"></script>

</body>

</html>